#!/usr/bin/env groovy|

pipeline {
    agent any
    environment {
	BUILD_MSG = 'Building.. ${env.BUILD_ID} on ${env.JENKINS_URL}'
    }

    stages {
        stage('Build') {
            steps {
                echo '${BUILD_MSG}'
		node ('cell'){
		    checkout scm
		    def cellImage = docker.build("cell-Image", "-f ./app/Dockerfile .")
		    cellImage.push()
	        }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing.. ${env.BUILD_ID}'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying.... ${env.BUILD_ID}'
            }
        }
    }
}
