#!/usr/bin/env groovy|

pipeline {

    agent none

    stages {
        stage('Build') {
            steps {
                echo 'Building.. ${env.BUILD_ID} on ${env.JENKINS_URL}'
		checkout scm
		def cellImage = docker.build("cell-Image", "./app/Dockerfile")
            }
        }
        stage('Test') {
            steps {
                echo 'Testing.. ${env.BUILD_ID}'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying.... ${env.BUILD_ID}'
		cellImage.push()
            }
        }
    }
}
