#!/usr/bin/env groovy|

node {
    def app

    stage('Clone') {
        checkout scm
    }

    stage('Build') {
        app = docker.build("cell-image", "./app/Dockerfile .")

    stage('Run tests') {
        app.inside {
            sh 'echo "Tests passed"'
        }
    }

    stage('Push') {
        docker
